 ERROR root [2018-01-29 00:30:56,135] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-29 00:30:56,246] - The following logs sent to logger failed:
  WARN root [2018-01-29 00:30:56,293] - ==> [2018-01-29 00:30:56 126] TCPPacketReceiver::processPendingEvents(10.82.25.163:52554): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-29 00:30:56,294] - ==> [2018-01-29 00:30:56 191] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-29 00:30:56,295] - TCPPacketReceiver::processPendingEvents(10.82.25.163:52558): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-29 00:30:56,295] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-29 00:30:56,305] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-29 00:30:56,326] - onLoginAppShutDown()
  INFO root [2018-01-29 00:30:56,326] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-29 00:30:56,326] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-29 00:30:56,328] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-29 00:30:56,329] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-29 00:30:56,329] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-29 00:30:56,329] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-29 00:30:56,329] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-29 00:30:56,330] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-29 00:30:56,330] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-29 00:30:56,331] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-29 00:30:56,456] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-29 00:30:56,457] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-01-29 13:20:58,502] - 
  INFO root [2018-01-29 13:20:58,543] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-29 13:20:58,544] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-29 13:20:58,544] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-29 13:20:58,545] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-29 13:20:58,547] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.82.25.163 ( 10.82.25.163:20013 )
  INFO root [2018-01-29 13:20:58,548] - NetworkInterface::initialize(EXTERNAL): address 10.82.25.163:20013, SOMAXCONN=128.
  INFO root [2018-01-29 13:20:58,549] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.82.25.163 ( 10.82.25.163:57437 )
  INFO root [2018-01-29 13:20:58,549] - NetworkInterface::initialize(INTERNAL): address 10.82.25.163:57437, SOMAXCONN=128.
  INFO root [2018-01-29 13:20:58,549] - server-configs:
  INFO root [2018-01-29 13:20:58,549] - 	internalAddr : 10.82.25.163:57437
  INFO root [2018-01-29 13:20:58,550] - 	externalAddr : 10.82.25.163:20013
  INFO root [2018-01-29 13:20:58,550] - 	componentID : 9000
  INFO root [2018-01-29 13:20:58,899] - Components::findLogger: found logger, addr:10.82.25.163:57418
  INFO root [2018-01-29 13:20:58,899] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-29 13:20:58,899] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-29 13:20:58,904] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 8536 ----
  INFO root [2018-01-29 13:20:58,904] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-29 13:20:58,904] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-29 13:20:58,905] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-29 13:20:59,087] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-29 13:20:59,089] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-29 13:20:59,090] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-29 13:20:59,097] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-29 13:20:59,097] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-29 13:20:59,097] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-29 13:20:59,100] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-29 13:20:59,171] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-29 13:20:59,241] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-29 13:20:59,241] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-29 13:20:59,246] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-29 13:20:59,246] - TelnetServer server is running on port 31000
  INFO root [2018-01-29 13:21:00,064] - ---- loginapp is running ----
 DEBUG root [2018-01-29 13:21:00,065] - Components::process(): Request for the process of identity...
  WARN root [2018-01-29 13:21:06,307] - Forwarding logs to logger[10.82.25.163:57418/0/0/0]...
 ERROR root [2018-01-29 13:38:34,270] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-29 13:38:34,340] - The following logs sent to logger failed:
  WARN root [2018-01-29 13:38:34,355] - ==> [2018-01-29 13:38:34 265] TCPPacketReceiver::processPendingEvents(10.82.25.163:57418): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-29 13:38:34,356] - ==> [2018-01-29 13:38:34 271] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-29 13:38:34,365] - TCPPacketReceiver::processPendingEvents(10.82.25.163:57424): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-29 13:38:34,370] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-29 13:38:34,391] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-29 13:38:34,423] - onLoginAppShutDown()
  INFO root [2018-01-29 13:38:34,423] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-29 13:38:34,423] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-29 13:38:34,424] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-29 13:38:34,424] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-29 13:38:34,425] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-29 13:38:34,425] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-29 13:38:34,425] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-29 13:38:34,425] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-29 13:38:34,425] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-29 13:38:34,425] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-29 13:38:34,531] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-29 13:38:34,532] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-01-29 13:50:09,817] - 
  INFO root [2018-01-29 13:50:09,823] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-29 13:50:09,824] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-29 13:50:09,825] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-29 13:50:09,825] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-29 13:50:09,910] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.82.25.163 ( 10.82.25.163:20013 )
  INFO root [2018-01-29 13:50:09,911] - NetworkInterface::initialize(EXTERNAL): address 10.82.25.163:20013, SOMAXCONN=128.
  INFO root [2018-01-29 13:50:09,913] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.82.25.163 ( 10.82.25.163:58788 )
  INFO root [2018-01-29 13:50:09,914] - NetworkInterface::initialize(INTERNAL): address 10.82.25.163:58788, SOMAXCONN=128.
  INFO root [2018-01-29 13:50:09,914] - server-configs:
  INFO root [2018-01-29 13:50:09,914] - 	internalAddr : 10.82.25.163:58788
  INFO root [2018-01-29 13:50:09,914] - 	externalAddr : 10.82.25.163:20013
  INFO root [2018-01-29 13:50:09,914] - 	componentID : 9000
  INFO root [2018-01-29 13:50:10,414] - Components::findLogger: found logger, addr:10.82.25.163:58784
  INFO root [2018-01-29 13:50:10,414] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-29 13:50:10,414] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-29 13:50:10,422] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 1860 ----
  INFO root [2018-01-29 13:50:10,422] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-29 13:50:10,422] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-29 13:50:10,423] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-29 13:50:10,578] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-29 13:50:10,579] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-29 13:50:10,580] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-29 13:50:10,587] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-29 13:50:10,588] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-29 13:50:10,588] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-29 13:50:10,590] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-29 13:50:10,665] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-29 13:50:10,709] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-29 13:50:10,709] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-29 13:50:10,712] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-29 13:50:10,712] - TelnetServer server is running on port 31000
  INFO root [2018-01-29 13:50:11,096] - ---- loginapp is running ----
 DEBUG root [2018-01-29 13:50:11,096] - Components::process(): Request for the process of identity...
  WARN root [2018-01-29 13:50:17,194] - Forwarding logs to logger[10.82.25.163:58784/0/0/0]...
 ERROR root [2018-01-29 13:55:13,166] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-29 13:55:13,173] - The following logs sent to logger failed:
  WARN root [2018-01-29 13:55:13,174] - ==> [2018-01-29 13:55:13 162] TCPPacketReceiver::processPendingEvents(10.82.25.163:58784): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-29 13:55:13,174] - ==> [2018-01-29 13:55:13 167] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-29 13:55:13,263] - TCPPacketReceiver::processPendingEvents(10.82.25.163:58781): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-29 13:55:13,273] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-29 13:55:13,276] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-29 13:55:13,277] - onLoginAppShutDown()
  INFO root [2018-01-29 13:55:13,277] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-29 13:55:13,277] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-29 13:55:13,278] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-29 13:55:13,278] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-29 13:55:13,278] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-29 13:55:13,278] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-29 13:55:13,279] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-29 13:55:13,279] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-29 13:55:13,279] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-29 13:55:13,279] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-29 13:55:13,296] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-29 13:55:13,296] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-29 13:55:13,597] - ThreadPool::destroy(): waiting for thread(2)[0x407ffa0,0x4080758,], try=1
