  INFO root [2018-01-30 14:14:07,005] - 
  INFO root [2018-01-30 14:14:07,030] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-30 14:14:07,567] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-30 14:14:07,568] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-30 14:14:07,568] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-30 14:14:07,874] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:20013 )
  INFO root [2018-01-30 14:14:07,926] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.133:20013, SOMAXCONN=128.
  INFO root [2018-01-30 14:14:07,928] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:60473 )
  INFO root [2018-01-30 14:14:07,928] - NetworkInterface::initialize(INTERNAL): address 192.168.1.133:60473, SOMAXCONN=128.
  INFO root [2018-01-30 14:14:07,928] - server-configs:
  INFO root [2018-01-30 14:14:07,928] - 	internalAddr : 192.168.1.133:60473
  INFO root [2018-01-30 14:14:07,928] - 	externalAddr : 192.168.1.133:20013
  INFO root [2018-01-30 14:14:07,928] - 	componentID : 9000
  INFO root [2018-01-30 14:14:08,496] - Components::findLogger: found logger, addr:192.168.1.133:60455
  INFO root [2018-01-30 14:14:08,497] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 14:14:08,497] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 14:14:09,109] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 15216 ----
  INFO root [2018-01-30 14:14:09,110] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-30 14:14:09,151] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-30 14:14:09,176] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-30 14:14:10,438] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 14:14:10,452] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 14:14:10,461] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 14:14:10,552] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 14:14:10,577] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 14:14:10,590] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 14:14:10,602] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 14:14:10,741] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 14:14:11,170] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-30 14:14:11,171] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-30 14:14:11,220] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-30 14:14:11,220] - TelnetServer server is running on port 31000
  INFO root [2018-01-30 14:14:11,659] - ---- loginapp is running ----
 DEBUG root [2018-01-30 14:14:11,659] - Components::process(): Request for the process of identity...
  WARN root [2018-01-30 14:14:17,781] - Forwarding logs to logger[192.168.1.133:60455/0/0/0]...
 ERROR root [2018-01-30 14:14:34,481] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 14:14:34,539] - The following logs sent to logger failed:
  WARN root [2018-01-30 14:14:34,539] - ==> [2018-01-30 14:14:34 470] TCPPacketReceiver::processPendingEvents(192.168.1.133:60455): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 14:14:34,539] - ==> [2018-01-30 14:14:34 481] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-30 14:14:34,594] - TCPPacketReceiver::processPendingEvents(192.168.1.133:60456): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 14:14:34,601] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 14:14:34,604] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-30 14:14:34,604] - onLoginAppShutDown()
  INFO root [2018-01-30 14:14:34,604] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-30 14:14:34,604] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-30 14:14:34,605] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 14:14:34,605] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 14:14:34,605] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 14:14:34,605] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 14:14:34,606] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 14:14:34,606] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 14:14:34,606] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 14:14:34,606] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 14:14:34,623] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-30 14:14:34,623] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-30 14:14:34,923] - ThreadPool::destroy(): waiting for thread(2)[0x3b19f38,0x3b19e68,], try=1
  INFO root [2018-01-30 14:14:38,072] - 
  INFO root [2018-01-30 14:14:38,076] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-30 14:14:38,077] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-30 14:14:38,078] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-30 14:14:38,078] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-30 14:14:38,082] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:20013 )
  INFO root [2018-01-30 14:14:38,082] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.133:20013, SOMAXCONN=128.
  INFO root [2018-01-30 14:14:38,085] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:60497 )
  INFO root [2018-01-30 14:14:38,085] - NetworkInterface::initialize(INTERNAL): address 192.168.1.133:60497, SOMAXCONN=128.
  INFO root [2018-01-30 14:14:38,086] - server-configs:
  INFO root [2018-01-30 14:14:38,086] - 	internalAddr : 192.168.1.133:60497
  INFO root [2018-01-30 14:14:38,086] - 	externalAddr : 192.168.1.133:20013
  INFO root [2018-01-30 14:14:38,086] - 	componentID : 9000
  INFO root [2018-01-30 14:14:39,905] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 12388 ----
  INFO root [2018-01-30 14:14:39,908] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-30 14:14:39,920] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-30 14:14:39,920] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-30 14:14:40,138] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 14:14:40,139] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 14:14:40,140] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 14:14:40,147] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 14:14:40,148] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 14:14:40,148] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 14:14:40,149] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 14:14:40,228] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 14:14:40,304] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-30 14:14:40,304] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-30 14:14:40,308] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-30 14:14:40,308] - TelnetServer server is running on port 31000
  WARN root [2018-01-30 14:14:40,329] - loginapp.cpp:171: Profile scriptCall took 0.02 seconds
  INFO root [2018-01-30 14:14:41,471] - ---- loginapp is running ----
 DEBUG root [2018-01-30 14:14:41,482] - Components::process(): Request for the process of identity...
  WARN root [2018-01-30 14:14:47,685] - event_dispatcher.cpp:171: Profile callSystemTimers took 0.02 seconds
  INFO root [2018-01-30 14:14:48,689] - Components::findComponents: find logger(1)...
  WARN root [2018-01-30 14:14:49,018] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20081, errorno=10048
  INFO root [2018-01-30 14:14:50,028] - Components::findComponents: find logger(2)...
  INFO root [2018-01-30 14:14:50,103] - Components::findComponents: found logger, addr:192.168.1.133:60499
  INFO root [2018-01-30 14:14:50,104] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 14:14:50,105] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 14:14:50,108] - Components::findComponents: find dbmgr(3)...
  INFO root [2018-01-30 14:14:50,217] - Components::findComponents: found dbmgr, addr:192.168.1.133:60494
  INFO root [2018-01-30 14:14:50,219] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 14:14:50,220] - Components::addComponent[dbmgr], uid=1, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 14:14:50,220] - Components::findComponents: found dbmgr, addr:192.168.1.133:60494
  WARN root [2018-01-30 14:14:51,220] - Forwarding logs to logger[192.168.1.133:60499/0/0/0]...
 ERROR root [2018-01-30 15:38:27,567] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 15:38:27,571] - The following logs sent to logger failed:
  WARN root [2018-01-30 15:38:27,572] - ==> [2018-01-30 15:38:27 562] TCPPacketReceiver::processPendingEvents(192.168.1.133:60499): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 15:38:27,572] - ==> [2018-01-30 15:38:27 567] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-30 15:38:27,627] - TCPPacketReceiver::processPendingEvents(192.168.1.133:60494): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 15:38:27,631] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 15:38:27,635] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-30 15:38:27,637] - onLoginAppShutDown()
  INFO root [2018-01-30 15:38:27,637] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-30 15:38:27,637] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-30 15:38:27,640] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 15:38:27,640] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 15:38:27,641] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 15:38:27,641] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 15:38:27,641] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 15:38:27,642] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 15:38:27,642] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 15:38:27,642] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 15:38:27,664] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-30 15:38:27,664] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-30 15:38:27,965] - ThreadPool::destroy(): waiting for thread(2)[0x389d4f8,0x389db10,], try=1
  INFO root [2018-01-30 15:38:46,864] - 
  INFO root [2018-01-30 15:38:46,870] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-30 15:38:46,873] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-30 15:38:46,874] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-30 15:38:46,874] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-30 15:38:46,969] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:20013 )
  INFO root [2018-01-30 15:38:46,970] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.133:20013, SOMAXCONN=128.
  INFO root [2018-01-30 15:38:46,972] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:54140 )
  INFO root [2018-01-30 15:38:46,973] - NetworkInterface::initialize(INTERNAL): address 192.168.1.133:54140, SOMAXCONN=128.
  INFO root [2018-01-30 15:38:46,973] - server-configs:
  INFO root [2018-01-30 15:38:46,973] - 	internalAddr : 192.168.1.133:54140
  INFO root [2018-01-30 15:38:46,973] - 	externalAddr : 192.168.1.133:20013
  INFO root [2018-01-30 15:38:46,973] - 	componentID : 9000
  INFO root [2018-01-30 15:38:48,792] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 10992 ----
  INFO root [2018-01-30 15:38:48,794] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-30 15:38:48,795] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-30 15:38:48,796] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-30 15:38:48,976] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 15:38:48,977] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 15:38:48,977] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 15:38:48,987] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 15:38:48,988] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 15:38:48,988] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 15:38:48,989] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 15:38:49,046] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 15:38:49,104] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-30 15:38:49,104] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-30 15:38:49,108] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-30 15:38:49,108] - TelnetServer server is running on port 31000
  WARN root [2018-01-30 15:38:49,143] - loginapp.cpp:171: Profile scriptCall took 0.04 seconds
  INFO root [2018-01-30 15:38:50,222] - ---- loginapp is running ----
 DEBUG root [2018-01-30 15:38:50,229] - Components::process(): Request for the process of identity...
  WARN root [2018-01-30 15:38:56,520] - event_dispatcher.cpp:171: Profile callSystemTimers took 0.03 seconds
  INFO root [2018-01-30 15:38:57,528] - Components::findComponents: find logger(1)...
  INFO root [2018-01-30 15:38:57,579] - Components::findComponents: found logger, addr:192.168.1.133:54139
  INFO root [2018-01-30 15:38:57,579] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 15:38:57,582] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 15:38:57,583] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-01-30 15:38:57,691] - Components::findComponents: found dbmgr, addr:192.168.1.133:54142
  INFO root [2018-01-30 15:38:57,691] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 15:38:57,692] - Components::addComponent[dbmgr], uid=1, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 15:38:57,692] - Components::findComponents: found dbmgr, addr:192.168.1.133:54142
  WARN root [2018-01-30 15:38:58,694] - Forwarding logs to logger[192.168.1.133:54139/0/0/0]...
 ERROR root [2018-01-30 15:40:16,067] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 15:40:16,074] - The following logs sent to logger failed:
  WARN root [2018-01-30 15:40:16,074] - ==> [2018-01-30 15:40:16 060] TCPPacketReceiver::processPendingEvents(192.168.1.133:54139): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 15:40:16,075] - ==> [2018-01-30 15:40:16 068] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-30 15:40:16,194] - TCPPacketReceiver::processPendingEvents(192.168.1.133:54142): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 15:40:16,203] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 15:40:16,220] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-30 15:40:16,226] - onLoginAppShutDown()
  INFO root [2018-01-30 15:40:16,227] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-30 15:40:16,227] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-30 15:40:16,227] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 15:40:16,228] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 15:40:16,228] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 15:40:16,228] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 15:40:16,228] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 15:40:16,229] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 15:40:16,229] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 15:40:16,229] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 15:40:16,249] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-30 15:40:16,249] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-30 15:40:16,550] - ThreadPool::destroy(): waiting for thread(2)[0x39cdff8,0x39ce338,], try=1
 DEBUG root [2018-01-30 15:40:16,955] - TPThread::~TPThread(): 0x39cdff8
 DEBUG root [2018-01-30 15:40:16,959] - TPThread::~TPThread(): 0x39ce338
 DEBUG root [2018-01-30 15:40:16,959] - ThreadPool::destroy(): successfully!
  INFO root [2018-01-30 15:40:19,935] - 
  INFO root [2018-01-30 15:40:19,936] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-30 15:40:19,937] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-30 15:40:19,937] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-30 15:40:19,937] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-30 15:40:19,941] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:20013 )
  INFO root [2018-01-30 15:40:19,942] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.133:20013, SOMAXCONN=128.
  INFO root [2018-01-30 15:40:19,944] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:54234 )
  INFO root [2018-01-30 15:40:19,944] - NetworkInterface::initialize(INTERNAL): address 192.168.1.133:54234, SOMAXCONN=128.
  INFO root [2018-01-30 15:40:19,945] - server-configs:
  INFO root [2018-01-30 15:40:19,945] - 	internalAddr : 192.168.1.133:54234
  INFO root [2018-01-30 15:40:19,945] - 	externalAddr : 192.168.1.133:20013
  INFO root [2018-01-30 15:40:19,945] - 	componentID : 9000
  INFO root [2018-01-30 15:40:21,801] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 9988 ----
  INFO root [2018-01-30 15:40:21,806] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-30 15:40:21,806] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-30 15:40:21,807] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-30 15:40:21,963] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 15:40:21,964] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 15:40:21,965] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 15:40:21,970] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 15:40:21,970] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 15:40:21,971] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 15:40:21,972] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 15:40:22,047] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 15:40:22,129] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-30 15:40:22,129] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-30 15:40:22,133] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-30 15:40:22,134] - TelnetServer server is running on port 31000
  INFO root [2018-01-30 15:40:23,279] - ---- loginapp is running ----
 DEBUG root [2018-01-30 15:40:23,290] - Components::process(): Request for the process of identity...
  INFO root [2018-01-30 15:40:29,513] - ServerApp::onHello: verInfo=1.1.0, scriptVerInfo=0.1.0, encryptedKey=None, addr:127.0.0.1:54251/0/0/0
  WARN root [2018-01-30 15:40:29,514] - Loginapp::onHello: client is not encrypted, addr=127.0.0.1:54251/0/0/0
  INFO root [2018-01-30 15:40:29,658] - Loginapp::loginFailed: loginName=a login is failed. failedcode=SERVER_ERR_SRV_NO_READY, datas=.
  INFO root [2018-01-30 15:40:30,513] - Components::findComponents: find logger(1)...
  INFO root [2018-01-30 15:40:30,610] - Components::findComponents: found logger, addr:192.168.1.133:54231
  INFO root [2018-01-30 15:40:30,611] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 15:40:30,611] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 15:40:30,612] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-01-30 15:40:30,715] - Components::findComponents: found dbmgr, addr:192.168.1.133:54227
  INFO root [2018-01-30 15:40:30,715] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 15:40:30,716] - Components::addComponent[dbmgr], uid=1, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 15:40:30,716] - Components::findComponents: found dbmgr, addr:192.168.1.133:54227
  WARN root [2018-01-30 15:40:31,717] - Forwarding logs to logger[192.168.1.133:54231/0/0/0]...
 ERROR root [2018-01-30 18:33:14,853] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 18:33:14,868] - The following logs sent to logger failed:
  WARN root [2018-01-30 18:33:14,868] - ==> [2018-01-30 18:33:14 848] TCPPacketReceiver::processPendingEvents(192.168.1.133:54231): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 18:33:14,869] - ==> [2018-01-30 18:33:14 855] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-30 18:33:14,969] - TCPPacketReceiver::processPendingEvents(192.168.1.133:54227): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 18:33:14,979] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 18:33:14,982] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-30 18:33:14,994] - onLoginAppShutDown()
  INFO root [2018-01-30 18:33:14,994] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-30 18:33:14,994] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-30 18:33:14,997] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 18:33:14,997] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 18:33:14,997] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 18:33:14,998] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 18:33:14,998] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 18:33:14,998] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 18:33:14,998] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 18:33:14,998] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 18:33:15,020] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-30 18:33:15,021] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-30 18:33:15,321] - ThreadPool::destroy(): waiting for thread(2)[0x3a0a438,0x3a0a0f8,], try=1
  INFO root [2018-01-30 18:33:19,610] - 
  INFO root [2018-01-30 18:33:19,622] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-30 18:33:19,623] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-30 18:33:19,623] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-30 18:33:19,624] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-30 18:33:19,714] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:20013 )
  INFO root [2018-01-30 18:33:19,714] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.133:20013, SOMAXCONN=128.
  INFO root [2018-01-30 18:33:19,717] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:60739 )
  INFO root [2018-01-30 18:33:19,717] - NetworkInterface::initialize(INTERNAL): address 192.168.1.133:60739, SOMAXCONN=128.
  INFO root [2018-01-30 18:33:19,718] - server-configs:
  INFO root [2018-01-30 18:33:19,718] - 	internalAddr : 192.168.1.133:60739
  INFO root [2018-01-30 18:33:19,718] - 	externalAddr : 192.168.1.133:20013
  INFO root [2018-01-30 18:33:19,718] - 	componentID : 9000
  INFO root [2018-01-30 18:33:20,801] - Components::findLogger: found logger, addr:192.168.1.133:60735
  INFO root [2018-01-30 18:33:20,801] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 18:33:20,801] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 18:33:20,843] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 11076 ----
  INFO root [2018-01-30 18:33:20,862] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-30 18:33:20,903] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-30 18:33:20,904] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-30 18:33:21,275] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 18:33:21,276] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 18:33:21,277] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 18:33:21,287] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 18:33:21,288] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 18:33:21,288] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 18:33:21,289] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 18:33:21,426] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 18:33:21,529] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-30 18:33:21,529] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-30 18:33:21,533] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-30 18:33:21,534] - TelnetServer server is running on port 31000
  WARN root [2018-01-30 18:33:21,622] - loginapp.cpp:171: Profile scriptCall took 0.09 seconds
  INFO root [2018-01-30 18:33:22,777] - ---- loginapp is running ----
 DEBUG root [2018-01-30 18:33:22,780] - Components::process(): Request for the process of identity...
  WARN root [2018-01-30 18:33:28,952] - Forwarding logs to logger[192.168.1.133:60735/0/0/0]...
 ERROR root [2018-01-30 20:52:23,942] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 20:52:23,952] - The following logs sent to logger failed:
  WARN root [2018-01-30 20:52:23,953] - ==> [2018-01-30 20:52:23 939] TCPPacketReceiver::processPendingEvents(192.168.1.133:60735): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 20:52:23,953] - ==> [2018-01-30 20:52:23 943] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-30 20:52:24,037] - TCPPacketReceiver::processPendingEvents(192.168.1.133:60733): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 20:52:24,044] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 20:52:24,049] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-30 20:52:24,051] - onLoginAppShutDown()
  INFO root [2018-01-30 20:52:24,052] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-30 20:52:24,052] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-30 20:52:24,054] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 20:52:24,055] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 20:52:24,055] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 20:52:24,056] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 20:52:24,056] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 20:52:24,056] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 20:52:24,056] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 20:52:24,057] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 20:52:24,078] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-30 20:52:24,078] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-30 20:52:24,379] - ThreadPool::destroy(): waiting for thread(2)[0x3a1a080,0x3a19cd8,], try=1
  INFO root [2018-01-30 20:52:27,690] - 
  INFO root [2018-01-30 20:52:27,701] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-30 20:52:27,702] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-30 20:52:27,714] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-30 20:52:27,714] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-30 20:52:27,738] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:20013 )
  INFO root [2018-01-30 20:52:27,739] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.133:20013, SOMAXCONN=128.
  INFO root [2018-01-30 20:52:27,742] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:52494 )
  INFO root [2018-01-30 20:52:27,742] - NetworkInterface::initialize(INTERNAL): address 192.168.1.133:52494, SOMAXCONN=128.
  INFO root [2018-01-30 20:52:27,743] - server-configs:
  INFO root [2018-01-30 20:52:27,743] - 	internalAddr : 192.168.1.133:52494
  INFO root [2018-01-30 20:52:27,743] - 	externalAddr : 192.168.1.133:20013
  INFO root [2018-01-30 20:52:27,743] - 	componentID : 9000
  INFO root [2018-01-30 20:52:29,589] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 11348 ----
  INFO root [2018-01-30 20:52:29,625] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-30 20:52:29,662] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-30 20:52:29,663] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-30 20:52:29,823] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 20:52:29,824] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 20:52:29,825] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 20:52:29,832] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 20:52:29,833] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 20:52:29,833] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 20:52:29,836] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 20:52:29,906] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 20:52:29,971] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-30 20:52:29,972] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-30 20:52:29,975] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-30 20:52:29,976] - TelnetServer server is running on port 31000
  INFO root [2018-01-30 20:52:30,642] - ---- loginapp is running ----
 DEBUG root [2018-01-30 20:52:30,653] - Components::process(): Request for the process of identity...
  INFO root [2018-01-30 20:52:37,835] - Components::findComponents: find logger(1)...
  INFO root [2018-01-30 20:52:37,921] - Components::findComponents: found logger, addr:192.168.1.133:52490
  INFO root [2018-01-30 20:52:37,921] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 20:52:37,921] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 20:52:37,922] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-01-30 20:52:38,028] - Components::findComponents: found dbmgr, addr:192.168.1.133:52487
  INFO root [2018-01-30 20:52:38,029] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 20:52:38,030] - Components::addComponent[dbmgr], uid=1, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 20:52:38,031] - Components::findComponents: found dbmgr, addr:192.168.1.133:52487
  WARN root [2018-01-30 20:52:39,032] - Forwarding logs to logger[192.168.1.133:52490/0/0/0]...
 ERROR root [2018-01-30 20:53:01,766] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 20:53:01,775] - The following logs sent to logger failed:
  WARN root [2018-01-30 20:53:01,775] - ==> [2018-01-30 20:53:01 764] TCPPacketReceiver::processPendingEvents(192.168.1.133:52490): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 20:53:01,776] - ==> [2018-01-30 20:53:01 766] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-30 20:53:01,852] - TCPPacketReceiver::processPendingEvents(192.168.1.133:52487): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 20:53:01,859] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 20:53:01,864] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-30 20:53:01,865] - onLoginAppShutDown()
  INFO root [2018-01-30 20:53:01,865] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-30 20:53:01,866] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-30 20:53:01,866] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 20:53:01,867] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 20:53:01,867] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 20:53:01,867] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 20:53:01,867] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 20:53:01,868] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 20:53:01,868] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 20:53:01,868] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 20:53:01,884] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-30 20:53:01,884] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-30 20:53:02,185] - ThreadPool::destroy(): waiting for thread(2)[0x3909928,0x390a1b0,], try=1
  INFO root [2018-01-30 20:53:05,334] - 
  INFO root [2018-01-30 20:53:05,353] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-30 20:53:05,354] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-30 20:53:05,357] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-30 20:53:05,358] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-30 20:53:05,376] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:20013 )
  INFO root [2018-01-30 20:53:05,376] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.133:20013, SOMAXCONN=128.
  INFO root [2018-01-30 20:53:05,381] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:52533 )
  INFO root [2018-01-30 20:53:05,382] - NetworkInterface::initialize(INTERNAL): address 192.168.1.133:52533, SOMAXCONN=128.
  INFO root [2018-01-30 20:53:05,382] - server-configs:
  INFO root [2018-01-30 20:53:05,382] - 	internalAddr : 192.168.1.133:52533
  INFO root [2018-01-30 20:53:05,382] - 	externalAddr : 192.168.1.133:20013
  INFO root [2018-01-30 20:53:05,382] - 	componentID : 9000
  INFO root [2018-01-30 20:53:07,169] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 15712 ----
  INFO root [2018-01-30 20:53:07,177] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-30 20:53:07,207] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-30 20:53:07,207] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-30 20:53:07,411] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 20:53:07,412] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 20:53:07,413] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 20:53:07,460] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 20:53:07,461] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 20:53:07,461] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 20:53:07,462] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 20:53:07,521] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 20:53:07,586] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-30 20:53:07,587] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-30 20:53:07,591] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-30 20:53:07,591] - TelnetServer server is running on port 31000
  WARN root [2018-01-30 20:53:07,614] - loginapp.cpp:171: Profile scriptCall took 0.02 seconds
  INFO root [2018-01-30 20:53:08,427] - ---- loginapp is running ----
 DEBUG root [2018-01-30 20:53:08,434] - Components::process(): Request for the process of identity...
  WARN root [2018-01-30 20:53:14,647] - event_dispatcher.cpp:171: Profile callSystemTimers took 0.04 seconds
  INFO root [2018-01-30 20:53:15,651] - Components::findComponents: find logger(1)...
  INFO root [2018-01-30 20:53:15,757] - Components::findComponents: found logger, addr:192.168.1.133:52537
  INFO root [2018-01-30 20:53:15,757] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 20:53:15,757] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 20:53:15,759] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-01-30 20:53:15,867] - Components::findComponents: found dbmgr, addr:192.168.1.133:52534
  INFO root [2018-01-30 20:53:15,868] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 20:53:15,868] - Components::addComponent[dbmgr], uid=1, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 20:53:15,869] - Components::findComponents: found dbmgr, addr:192.168.1.133:52534
  WARN root [2018-01-30 20:53:16,869] - Forwarding logs to logger[192.168.1.133:52537/0/0/0]...
 ERROR root [2018-01-30 20:53:37,731] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 20:53:37,737] - The following logs sent to logger failed:
  WARN root [2018-01-30 20:53:37,738] - ==> [2018-01-30 20:53:37 728] TCPPacketReceiver::processPendingEvents(192.168.1.133:52537): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 20:53:37,738] - ==> [2018-01-30 20:53:37 731] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-30 20:53:37,825] - TCPPacketReceiver::processPendingEvents(192.168.1.133:52534): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 20:53:37,827] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 20:53:37,831] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-30 20:53:37,831] - onLoginAppShutDown()
  INFO root [2018-01-30 20:53:37,831] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-30 20:53:37,832] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-30 20:53:37,832] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 20:53:37,832] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 20:53:37,832] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 20:53:37,833] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 20:53:37,833] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 20:53:37,833] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 20:53:37,833] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 20:53:37,833] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 20:53:37,849] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-30 20:53:37,850] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-30 20:53:38,150] - ThreadPool::destroy(): waiting for thread(2)[0x3877a50,0x3877b20,], try=1
  INFO root [2018-01-30 20:53:41,016] - 
  INFO root [2018-01-30 20:53:41,017] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-30 20:53:41,019] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-30 20:53:41,019] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-30 20:53:41,019] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-30 20:53:41,039] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:20013 )
  INFO root [2018-01-30 20:53:41,039] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.133:20013, SOMAXCONN=128.
  INFO root [2018-01-30 20:53:41,042] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:52568 )
  INFO root [2018-01-30 20:53:41,042] - NetworkInterface::initialize(INTERNAL): address 192.168.1.133:52568, SOMAXCONN=128.
  INFO root [2018-01-30 20:53:41,042] - server-configs:
  INFO root [2018-01-30 20:53:41,042] - 	internalAddr : 192.168.1.133:52568
  INFO root [2018-01-30 20:53:41,043] - 	externalAddr : 192.168.1.133:20013
  INFO root [2018-01-30 20:53:41,043] - 	componentID : 9000
  INFO root [2018-01-30 20:53:42,913] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 15064 ----
  INFO root [2018-01-30 20:53:42,921] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-30 20:53:42,922] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-30 20:53:42,922] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-30 20:53:43,076] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 20:53:43,077] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 20:53:43,078] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 20:53:43,084] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 20:53:43,085] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 20:53:43,086] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 20:53:43,087] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 20:53:43,149] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 20:53:43,221] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-30 20:53:43,221] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-30 20:53:43,224] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-30 20:53:43,225] - TelnetServer server is running on port 31000
  INFO root [2018-01-30 20:53:44,092] - ---- loginapp is running ----
 DEBUG root [2018-01-30 20:53:44,093] - Components::process(): Request for the process of identity...
  WARN root [2018-01-30 20:53:50,279] - event_dispatcher.cpp:171: Profile callSystemTimers took 0.03 seconds
  INFO root [2018-01-30 20:53:50,284] - ServerApp::onHello: verInfo=1.1.0, scriptVerInfo=0.1.0, encryptedKey=None, addr:127.0.0.1:52589/0/0/0
  WARN root [2018-01-30 20:53:50,285] - Loginapp::onHello: client is not encrypted, addr=127.0.0.1:52589/0/0/0
  INFO root [2018-01-30 20:53:50,449] - Loginapp::loginFailed: loginName=a login is failed. failedcode=SERVER_ERR_SRV_NO_READY, datas=.
  INFO root [2018-01-30 20:53:51,284] - Components::findComponents: find logger(1)...
  INFO root [2018-01-30 20:53:51,376] - Components::findComponents: found logger, addr:192.168.1.133:52571
  INFO root [2018-01-30 20:53:51,376] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 20:53:51,376] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 20:53:51,377] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-01-30 20:53:51,480] - Components::findComponents: found dbmgr, addr:192.168.1.133:52575
  INFO root [2018-01-30 20:53:51,480] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 20:53:51,480] - Components::addComponent[dbmgr], uid=1, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 20:53:51,480] - Components::findComponents: found dbmgr, addr:192.168.1.133:52575
  WARN root [2018-01-30 20:53:52,484] - Forwarding logs to logger[192.168.1.133:52571/0/0/0]...
 ERROR root [2018-01-30 21:25:11,960] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 21:25:11,964] - The following logs sent to logger failed:
  WARN root [2018-01-30 21:25:11,965] - ==> [2018-01-30 21:25:11 950] TCPPacketReceiver::processPendingEvents(192.168.1.133:52571): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 21:25:11,965] - ==> [2018-01-30 21:25:11 961] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-30 21:25:12,135] - TCPPacketReceiver::processPendingEvents(192.168.1.133:52575): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 21:25:12,145] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 21:25:12,152] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-30 21:25:12,155] - onLoginAppShutDown()
  INFO root [2018-01-30 21:25:12,155] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-30 21:25:12,156] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-30 21:25:12,156] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 21:25:12,156] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 21:25:12,156] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 21:25:12,157] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 21:25:12,157] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 21:25:12,157] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 21:25:12,158] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 21:25:12,158] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 21:25:12,175] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-30 21:25:12,175] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-30 21:25:12,477] - ThreadPool::destroy(): waiting for thread(2)[0x3a2bf18,0x3a2c0b8,], try=1
 DEBUG root [2018-01-30 21:25:12,888] - TPThread::~TPThread(): 0x3a2bf18
 DEBUG root [2018-01-30 21:25:12,892] - TPThread::~TPThread(): 0x3a2c0b8
 DEBUG root [2018-01-30 21:25:12,938] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-01-30 21:25:12,967] - Bundle::destroyObjPool(): size 12.
 DEBUG root [2018-01-30 21:25:12,967] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-01-30 21:25:12,968] - TCPPacket::destroyObjPool(): size 1.
 DEBUG root [2018-01-30 21:25:12,968] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-01-30 21:25:12,968] - EndPoint::destroyObjPool(): size 14.
 DEBUG root [2018-01-30 21:25:12,968] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-01-30 21:25:12,969] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-01-30 21:25:12,969] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-01-30 21:25:12,969] - loginapp(9000) has shut down.
  INFO root [2018-01-30 21:25:50,499] - 
  INFO root [2018-01-30 21:25:50,502] - -----------------------------------------------------------------------------------------


  INFO root [2018-01-30 21:25:50,503] - Resmgr::initialize: KBE_ROOT=G:/GitHub/kbengine/
  INFO root [2018-01-30 21:25:50,503] - Resmgr::initialize: KBE_RES_PATH=G:/GitHub/kbengine/kbe/res/;G:/GitHub/kbengine/newgame-assets/;G:/GitHub/kbengine/newgame-assets/scripts/;G:/GitHub/kbengine/newgame-assets/res/
  INFO root [2018-01-30 21:25:50,504] - Resmgr::initialize: KBE_BIN_PATH=G:/GitHub/kbengine/kbe/bin/server/
  INFO root [2018-01-30 21:25:50,521] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:20013 )
  INFO root [2018-01-30 21:25:50,521] - NetworkInterface::initialize(EXTERNAL): address 192.168.1.133:20013, SOMAXCONN=128.
  INFO root [2018-01-30 21:25:50,525] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.1.133 ( 192.168.1.133:55511 )
  INFO root [2018-01-30 21:25:50,526] - NetworkInterface::initialize(INTERNAL): address 192.168.1.133:55511, SOMAXCONN=128.
  INFO root [2018-01-30 21:25:50,526] - server-configs:
  INFO root [2018-01-30 21:25:50,526] - 	internalAddr : 192.168.1.133:55511
  INFO root [2018-01-30 21:25:50,527] - 	externalAddr : 192.168.1.133:20013
  INFO root [2018-01-30 21:25:50,528] - 	componentID : 9000
  INFO root [2018-01-30 21:25:52,364] - ---- loginapp Version: 1.1.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:59:38 Dec  1 2017. AppID: 9000. UID: 1. PID: 14592 ----
  INFO root [2018-01-30 21:25:52,364] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-01-30 21:25:52,365] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-01-30 21:25:52,365] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-01-30 21:25:52,527] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 21:25:52,528] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 21:25:52,528] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 21:25:52,533] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 21:25:52,534] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 21:25:52,534] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 21:25:52,535] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 21:25:52,590] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 21:25:52,652] - Script::install(): is successfully, Python=(3.4.2 (default, Dec  1 2017, 23:59:35) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-01-30 21:25:52,652] - Script::install(): KBExtra is successfully!
S_INFO root [2018-01-30 21:25:52,656] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-01-30 21:25:52,656] - TelnetServer server is running on port 31000
  INFO root [2018-01-30 21:25:53,748] - ---- loginapp is running ----
 DEBUG root [2018-01-30 21:25:53,752] - Components::process(): Request for the process of identity...
  INFO root [2018-01-30 21:26:00,956] - Components::findComponents: find logger(1)...
  INFO root [2018-01-30 21:26:00,997] - Components::findComponents: found logger, addr:192.168.1.133:55518
  INFO root [2018-01-30 21:26:00,998] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 21:26:00,998] - Components::addComponent[logger], uid=1, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 21:26:00,999] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-01-30 21:26:01,109] - Components::findComponents: found dbmgr, addr:192.168.1.133:55516
  INFO root [2018-01-30 21:26:01,110] - Components::addComponent: reset orderLog, uid=1!
  INFO root [2018-01-30 21:26:01,110] - Components::addComponent[dbmgr], uid=1, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-01-30 21:26:01,110] - Components::findComponents: found dbmgr, addr:192.168.1.133:55516
  WARN root [2018-01-30 21:26:02,111] - Forwarding logs to logger[192.168.1.133:55518/0/0/0]...
 ERROR root [2018-01-30 21:30:06,819] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 21:30:06,820] - The following logs sent to logger failed:
  WARN root [2018-01-30 21:30:06,820] - ==> [2018-01-30 21:30:06 817] TCPPacketReceiver::processPendingEvents(192.168.1.133:55518): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 21:30:06,821] - ==> [2018-01-30 21:30:06 820] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-01-30 21:30:06,929] - TCPPacketReceiver::processPendingEvents(192.168.1.133:55516): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-01-30 21:30:06,936] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-01-30 21:30:06,937] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-01-30 21:30:06,938] - onLoginAppShutDown()
  INFO root [2018-01-30 21:30:06,938] - Shutdowner::onShutdown: shutting down
  INFO root [2018-01-30 21:30:06,939] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-01-30 21:30:06,939] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-01-30 21:30:06,939] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-01-30 21:30:06,940] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-01-30 21:30:06,940] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-01-30 21:30:06,940] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-01-30 21:30:06,940] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-01-30 21:30:06,941] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-01-30 21:30:06,941] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-01-30 21:30:06,961] - Script::uninstall(): is successfully!
 DEBUG root [2018-01-30 21:30:06,962] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-01-30 21:30:07,262] - ThreadPool::destroy(): waiting for thread(2)[0x3769d60,0x376a5e8,], try=1
